### PR TITLE
feat: spawn pouchdb server from here

### PR DESCRIPTION
**Pull request by jo**
Before the pouchdb server was spawned from kazana. Doing it here enables the use
of the server from within the tests.

Depends on https://github.com/hoodiehq/spawn-pouchdb-server/pull/16

### CODE REVIEW

**Comment by jo** [comment]
This is a false positive: https://travis-ci.org/eHealthAfrica/kazana-server/builds/85356548#L167

**Comment by patriciagarcia** [comment]
@jo, hoodiehq/spawn-pouchdb-server#16 has been merged, can this be merged too or is still WIP?

**Comment by jo** [comment]
I would love to hear what @gr2m thinks about this

**Comment by gr2m** [comment]
gut feeling tells me that we should leave `spawn-pouchdb-server` in `kazana`. For tests in `kazana-server`, make spawn-pouchdb-server a devDependency and spawn it before running tests. But I might be wrong with this, happy to chat if you disagree

**Comment by jo** [comment]
@gr2m lets chat about this.
Kazana itself does not expose a method to start the server, it only comes with a binary. For the tests we need a way to programatically start and stop the server. And here's the best place for this I think.

**Pull request merged**
